# Copyright (c) 2021 aasaam software development group
image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$QUAY_HUB_USER --password=$QUAY_HUB_PASS quay.io
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    # build
    - docker build -f Dockerfile -t aasaam/rest-captcha .
    # push
    - |
      docker push aasaam/rest-captcha
      docker image tag aasaam/rest-captcha quay.io/aasaam/rest-captcha
      docker push quay.io/aasaam/rest-captcha
      docker image tag aasaam/rest-captcha docker.pkg.github.com/aasaam/rest-captcha/rest-captcha
      docker push docker.pkg.github.com/aasaam/rest-captcha/rest-captcha
      docker image tag aasaam/rest-captcha $CI_REGISTRY/aasaam/rest-captcha:latest
      docker push $CI_REGISTRY/aasaam/rest-captcha:latest
    # remove image
    - docker rmi aasaam/rest-captcha
  coverage: '/TOTAL_COVERAGE_FOR_CI_F: \d+\.\d+/'
